// <auto-generated />
namespace odh_foundation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class start : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(start));
        
        string IMigrationMetadata.Id
        {
            get { return "202306031107574_start"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
