// <auto-generated />
namespace odh_foundation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class dgsdfg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dgsdfg));
        
        string IMigrationMetadata.Id
        {
            get { return "202306180122047_dgsdfg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
