// <auto-generated />
namespace odh_foundation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class messagetab : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(messagetab));
        
        string IMigrationMetadata.Id
        {
            get { return "202307201820486_messagetab"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
